# Generated by Django 5.2.3 on 2025-06-19 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, db_comment="URL de la photo de l'auteur", max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descriptif', models.TextField(blank=True, db_comment='Description de la catégorie', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Joueurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('professionnel', 'Professionnel'), ('particulier', 'Particulier')], default='particulier', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Jeux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('annee_sortie', models.IntegerField(blank=True, null=True)),
                ('photo_boite', models.URLField(blank=True, db_comment='URL de la photo de la boîte', max_length=255, null=True)),
                ('editeur', models.CharField(blank=True, max_length=100, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludotheque.auteurs')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludotheque.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(db_comment='Note entre 1 et 5')),
                ('contenu', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('jeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.jeux')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.joueurs')),
            ],
        ),
        migrations.CreateModel(
            name='ListeJeux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('jeu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludotheque.jeux')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludotheque.joueurs')),
            ],
        ),
    ]
